version: "3"
services:
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./cfg/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./cfg/rules.yml:/etc/prometheus/rules.yml
    ports:
      - 9090:9090

  zipkin:
    image: openzipkin/zipkin
    container_name: zipkin
    ports:
      - "9411:9411" # Expose the Zipkin UI port
